### ISSUE TITLE
CODEBASE-LARAVEL-BLADE-MYSQL

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#10]
## TASKS

- [x] Crea-una-guia-de-instalacion-codebase, en la carpeta compartide de #1 
- [x] Crea-un-proyecto-de-laravel 
- [x] #13

**Comment by AngelDabnee** [comment]
EVIDENCIA DE PROBAR EL CODEBASE TASK 1. 
<img width="1440" alt="Captura de pantalla 2024-02-16 a la(s) 5 57 17 p m" src="https://github.com/REUBATCODE/leify/assets/114833669/fea21d6c-b4f4-43e6-9e6f-d36d1676aad4">
