### ISSUE TITLE
laravel-breeze-blade

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#13]
### Tasks
- Descargar e instalar nuevas dependencias
```php
composer install
npm install
```
- Configurar tu base de datos local con un nuevo usuario, y crea la base de datos
> [ ver como crear un nuevo usuario mysql ](https://shorturl.at/fqwNZ)
> puedes hacer un nuevo usuario mysql,  usario: leify, pwd:leify, base de datos, leify 
- Configurar el archivo .env de acuerdo a tus credenciales de mysql
-  Hacer migraciones
 ```php
php artisan migrate
```
- registrar un usuario exitosamente 
- tomar captura y comentar en este issue al dashboard para validar que lo probaste localmente

**Comment by JEstebanSanti** [comment]
![Captura desde 2024-02-16 22-09-54](https://github.com/REUBATCODE/leify/assets/78988823/2bca37af-6af7-488a-8d53-2ee58d0419c0)

**Comment by AngelDabnee** [comment]
Se realizó con éxito. 
<img width="1440" alt="Captura de pantalla 2024-02-17 a la(s) 10 12 28 a m" src="https://github.com/REUBATCODE/leify/assets/114833669/37b5b601-b0c9-47ce-925e-ff0bc116d445">
