### ISSUE TITLE
US-51-vista index de artistas

### ISSUE THREAD

**Issue by AngelDabnee** [REUBATCODE/leify#32]
Mostrar lista de los usuarios artistas que están registrados.

**Comment by ivanchenoweth** [comment]
No esta bien definido en la descripcion, ni tampoco bien configurado. Sin asignar, sin etiquetas sin proyecto, sin milestone

**Comment by AngelDabnee** [comment]
Index de vista artista terminada. 
Se realizó una uniData, para estar probando según la información que tuvieramos en la base de datos, 
<img width="1440" alt="Captura de pantalla 2024-03-02 a la(s) 7 06 03 p m" src="https://github.com/REUBATCODE/leify/assets/114833669/563f7044-bdca-4e3a-ac36-3b8e187db1f9">

**Comment by ivanchenoweth** [comment]
OK
